FROM ghcr.io/astral-sh/uv:python3.13-bookworm-slim AS builder

ENV UV_COMPILE_BYTECODE=1 
ENV UV_LINK_MODE=copy
ENV UV_PYTHON_DOWNLOADS=0

WORKDIR  /app

RUN --mount=type=cache,target=/root/.cache/uv \
  --mount=type=bind,source=./api/uv.lock,target=uv.lock \
  --mount=type=bind,source=./api/pyproject.toml,target=pyproject.toml \
  uv sync --frozen --no-install-project --no-dev --no-install-package core

COPY ./core /app/core
COPY ./api /app/api
WORKDIR /app/api/

RUN --mount=type=cache,target=/root/.cache/uv \
  uv sync --frozen --no-dev


FROM python:3.13-slim-bookworm

COPY --from=builder --chown=app:app /app/api /app/api
COPY --from=builder --chown=app:app /app/.venv /app/api/.venv

WORKDIR /app/api/

ENV PATH="/app/api/.venv/bin:$PATH"

CMD [ "uvicorn", "main:app", "--app-dir", "/home/bojanb/Programming/projects/code-context/api/src", "--host", "0.0.0.0", "--port", "8080", "--log-level", "info"]
